// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lilluuevekimkmhdxaks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpbGx1dWV2ZWtpbWttaGR4YWtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDAwODUsImV4cCI6MjA3MzUxNjA4NX0.1spGoWFx1s1OLEfFcjks1IVx8G-E1aibHPMCWa_bPfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});